# Docker Compose for development hosting
version: "3"
services:
  database:
    container_name: database
    image: postgres:10.7
    environment:
      - POSTGRES_DB=${NODE_ENV}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - "5432"
    ports:
      - "5432:5432"