# Docker Compose for development hosting
version: "3"
services:
  database:
    container_name: database
    image: postgres:12.2
    environment:
      - POSTGRES_DB=${APP_NAME}-${NODE_ENV}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - "5432"
    ports:
      - "5432:5432"