service: ${env:APP_NAME}

plugins:
  - serverless-domain-manager
  - serverless-aws-static-file-handler/plugins/BinaryMediaTypes
  - serverless-offline

custom:
  customDomain:
    domainName: ${env:DOMAIN_NAME}
    certificateName: ${env:APP_NAME}.com
    createRoute53Record: true
  apiGateway:
    binaryMediaTypes:
      - "*/*"

provider:
  name: aws
  stage: ${env:NODE_ENV}
  runtime: nodejs12.x
  timeout: 10
  logRetentionInDays: 30
  usagePlan:
    quota:
      limit: 1000
      period: DAY
    throttle:
      rateLimit: 100
      burstLimit: 1000
  environment:
    APP_NAME: ${env:APP_NAME}
    NODE_ENV: ${env:NODE_ENV}
    API_KEY: ${env:API_KEY}
    DB_HOST: ${env:DB_HOST}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}

functions:
  public:
    handler: build/public/index.default
    events:
      - http:
          path: /
          method: GET
          cors: true
      - http:
          path: /{filePath+}
          method: GET
          cors: true
  api-health-check:
    handler: build/api/routes/health-check.default
    events:
      - http:
          path: /api/health-check
          method: GET
          cors: true
  api-login:
    handler: build/api/routes/login.default
    events:
      - http:
          path: /api/login
          method: POST
          cors: true
  api-update:
    handler: build/api/routes/update.default
    events:
      - http:
          path: /api/update
          method: POST
          cors: true